name: Cypress Tests

on: 
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress node command line
        default: node runner.js

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.18.0-chrome-139.0.7258.127-1-ff-141.0.3-edge-139.0.3405.86-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v5.0.0

      - name: Install denpendencies
        run: yarn install

      - name: Run E2E tests
        run: ${{ github.event.inputs.cli }}
