name: Cypress Tests

on: 
  workflow_dispatch:

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.18.0-chrome-139.0.7258.127-1-ff-141.0.3-edge-139.0.3405.86-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v5.0.0
      
      - name: Install denpendencies
        run: yarn install
      
      - name: Run E2E tests
        run: node runner-electron.js
    env:
      TARGET_TOKEN_ELECTRON: ${{ secrets.TARGET_TOKEN_ELECTRON }}

  cypress-chrome-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.18.0-chrome-139.0.7258.127-1-ff-141.0.3-edge-139.0.3405.86-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v5.0.0
      
      - name: Install denpendencies
        run: yarn install
      
      - name: Run E2E tests
        run: node runner-electron.js
    env:
      TARGET_TOKEN_CHROME: ${{ secrets.TARGET_TOKEN_CHROME }}

  cypress-edge-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.18.0-chrome-139.0.7258.127-1-ff-141.0.3-edge-139.0.3405.86-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v5.0.0
      
      - name: Install denpendencies
        run: yarn install
      
      - name: Run E2E tests
        run: node runner-electron.js
    env:
      TARGET_TOKEN_EDGE: ${{ secrets.TARGET_TOKEN_EDGE }}

  cypress-firefox-tests:
    needs: cypress-electron-tests
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.18.0-chrome-139.0.7258.127-1-ff-141.0.3-edge-139.0.3405.86-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v5.0.0
      
      - name: Install denpendencies
        run: yarn install
      
      - name: Run E2E tests
        run: node runner-electron.js
    env:
      TARGET_TOKEN_FIREFOX: ${{ secrets.TARGET_TOKEN_FIREFOX }}
